---
- name: Play to check connectivity
  hosts: all
  any_errors_fatal: true
  gather_facts: false
  tags: find_user
  become: false
  tasks:
    - name: SET_FACT; set python interpreter
      ansible.builtin.set_fact: ansible_python_interpreter="/usr/bin/python3"

    - name: WAIT_FOR; Wait for ssh to be available and connect
      ansible.builtin.wait_for:
        port: 22
        host: "{{ (ansible_ssh_host | default(ansible_host)) | default(inventory_hostname) }}"
        search_regex: OpenSSH
        delay: 10
        timeout: 600
      connection: local
    

    - name: PAUSE; because Jetstream 2 networking
      ansible.builtin.pause:
        minutes: 1
      
    - include_tasks: find_connection.yml
      loop: "{{ CONNECTION_USERNAMES }}"

    - name: FAIL; fail when unable to connect via ssh
      ansible.builtin.fail:
        msg: "?Could not find a valid ansible_user for subsequent ssh connections; exiting playbook."
      when: ansible_user is not defined


- name: Play to install dplpy and its requirements
  hosts: all
  any_errors_fatal: true
  gather_facts: false
  tags: install_dplpy
  become: false
  tasks:
    - name: SET_FACT; set python interpreter
      ansible.builtin.set_fact: ansible_python_interpreter="/usr/bin/python3"

    - name: Install dplpy from pip
      ansible.builtin.pip:
        name: dplpy


- name: Play to install dplr and its requirements
  hosts: all
  any_errors_fatal: true
  gather_facts: false
  tags: install_dplr
  become: true
  tasks:
    - name: Update apt packages
      shell: apt update

    - name: Download and Install R
      shell: apt install r-base r-base-dev -y

    - name: Install XML
      shell: apt-get install r-cran-xml

    - name: Install dplR
      shell: Rscript -e 'install.packages("dplR", repos="http://cran.us.r-project.org")'
